### ISSUE TITLE
Crashes in POSTPR

### ISSUE THREAD

**Issue by kyrsjo** [SixTrack/SixTrack#249]
When running without CRLIBM, I sometimes see crashes in POSTPR with the following backtrace:
```
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x95b8b0 in ???
#1  0x95aff5 in ???
#2  0x9e6a0f in ???
#3  0x60fae3 in postpr_
        at /home/kyrsjo/code/SixTrack2/SixTrack/SixTrack_cmakesix_BUILD_TESTING_NOCRLIBM_defaultcompiler_debug/sixve.f:29175
#4  0x7c808e in maincr
        at /home/kyrsjo/code/SixTrack2/SixTrack/SixTrack_cmakesix_BUILD_TESTING_NOCRLIBM_defaultcompiler_debug/sixve.f:8546
#5  0x7c84ab in main
        at /home/kyrsjo/code/SixTrack2/SixTrack/SixTrack_cmakesix_BUILD_TESTING_NOCRLIBM_defaultcompiler_debug/sixve.f:8704
SixTrack finished running: 136
```

The line in question reads:
```
 600  if((((numl+1)/iskip)/(iab-iaa))/iav.gt.nlya) nstop=iav*nlya        !hr06
```

This happens for several tests, including `beam-HO_6D-newstyle` (about to be merged in PR #246 ). The POST block in fort.3 looks like:
```
POSTPROCESSING----------------------------------------------------------
LHC Dynamic Aperture at Injection Version 5 (1998)
20 0 0 1 .08 .08 1 0 0 1. 1.
64. 59. 1 1 10 .005 1 .050
0 1 0 1 1 1 1 1 30
NEXT
```

I'm putting it here to remember. It may be that the problem is always there (not only when not using CRLIBM), it's just that we don't normally run with debugging on.

**Comment by JamesMolson** [comment]
iab and iaa are both zero, so you divide by zero.
